#!/usr/bin/env python
"""Generate the README/docs assets from a REAL offline demo run.

Produces:
  - docs/assets/specter-demo.svg   (terminal screenshot via Rich's SVG export)
  - docs/example-report.md         (the generated risk report from the run)

Deterministic, fully offline (built-in echo model + simulated/demo tools),
no API keys, no network. Run:  python scripts/capture_screenshot.py
"""
from __future__ import annotations

import io
import os
import shutil
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ASSETS = REPO / "docs" / "assets"


def main() -> int:
    ASSETS.mkdir(parents=True, exist_ok=True)
    tmp = Path(tempfile.mkdtemp(prefix="specter-shot-"))
    # Set SPECTER_HOME BEFORE importing specter so runs/db/cache land in tmp.
    os.environ["SPECTER_HOME"] = str(tmp)

    from rich.console import Console

    import specter.cli as cli
    from specter.config import RUNS_DIR
    from specter.runstore import latest_run_id

    # Route all CLI output into a recording console we can export to SVG.
    rec = Console(record=True, width=118, file=io.StringIO(), force_terminal=True)
    cli.console = rec  # replace the module-global console used by all commands

    cli.quickstart()                       # full offline+demo engagement
    cli.findings(run_id="", status="")     # render the team findings table

    out_svg = ASSETS / "specter-demo.svg"
    rec.save_svg(str(out_svg), title="specter quickstart")
    print(f"wrote {out_svg.relative_to(REPO)} ({out_svg.stat().st_size} bytes)")

    # Second asset: showcase the specialist agents, cloud audit, and MCP suite
    # so the README reflects the full capability surface — still fully offline.
    feat = Console(record=True, width=118, file=io.StringIO(), force_terminal=True)
    cli.console = feat
    try:
        cli.agents()
        cli.cloud(provider="aws", demo=True, report=False)
        cli.mcp_suite_list()
    except Exception as e:  # never let the asset build break the demo build
        feat.print(f"[red]feature capture error: {e}[/red]")
    feat_svg = ASSETS / "specter-features.svg"
    feat.save_svg(str(feat_svg), title="specter — agents · cloud · mcp suite")
    print(f"wrote {feat_svg.relative_to(REPO)} ({feat_svg.stat().st_size} bytes)")
    cli.console = rec  # restore for any later use

    rid = latest_run_id()
    if rid:
        risk = RUNS_DIR / rid / "risk.md"
        if risk.exists():
            dst = REPO / "docs" / "example-report.md"
            header = (
                "---\nlayout: default\ntitle: \"Example report — Specter AI\"\n---\n\n"
                "<!-- Generated by scripts/capture_screenshot.py from a real "
                "offline demo run (echo model + simulated tools). -->\n\n"
            )
            dst.write_text(header + risk.read_text())
            print(f"wrote {dst.relative_to(REPO)} ({dst.stat().st_size} bytes)")

    shutil.rmtree(tmp, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
